store_dirver: mysql

# mongo_dirver:
#     host: 127.0.0.1
#     port: 27017
#     name: root
#     table: filter_word
#     username: root
#     password: 123456
#     timeout: 1

mysql_dirver:
  host: 127.0.0.1
  port: 3306
  name: test
  table: filter_word
  username: root
  password: yourpasswd
  timeout: 1

filter: aca 

#jieba
jieba_filter:
    dict: dict

interval: 5

server:
  host: 127.0.0.1
  port: 9511